#!/usr/bin/env bash
# Generated by scripts/build-installer.sh — do not edit directly.
# Run on a fresh NixOS live ISO to bootstrap the system.
set -euo pipefail

if [ "${EUID:-$(id -u)}" -ne 0 ]; then
  echo "This installer must run as root."
  echo "Use: curl -fL https://raw.githubusercontent.com/zhogoshi/dotfiles/main/install.sh | sudo bash"
  exit 1
fi

DEST=""
USERNAME=""
INIT_PASS=""
KB_LAYOUT="us"
BROWSER_CHOICE=""
PRIMARY_DISK=""
PRIMARY_DEV=""
INSTALL_OK=0
WARNINGS=()
CRITICALS=()
RUN_TMP=""
FAIL_DETAIL_LABELS=()
FAIL_DETAIL_FILES=()

# ── Colors & TUI ─────────────────────────────────────────────────────────────

R='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
CY='\033[36m'
GR='\033[32m'
YE='\033[33m'
RE='\033[31m'

hide_cursor()  { printf '\033[?25l'; }
show_cursor()  { printf '\033[?25h'; }
clear_screen() { printf '\033[2J\033[H'; }

trap 'show_cursor; rm -rf "${RUN_TMP}" 2>/dev/null || true' EXIT

_abort_install() {
  show_cursor
  clear_screen
  rm -rf "$RUN_TMP" 2>/dev/null || true
  printf '%s\n' "Aborting installation..."
  trap - INT TERM
  exit 130
}
trap '_abort_install' INT TERM

_init_run_tmp() {
  [ -n "$RUN_TMP" ] && return 0
  RUN_TMP="$(mktemp -d "${TMPDIR:-/tmp}/nixsetup.XXXXXX")" || RUN_TMP="${TMPDIR:-/tmp}"
}

_capt() {
  local label="$1" lf
  shift
  _init_run_tmp
  lf="$(mktemp "$RUN_TMP/cap.XXXXXX")"
  if "$@" >"$lf" 2>&1; then
    rm -f "$lf"
    return 0
  fi
  FAIL_DETAIL_LABELS+=("$label")
  FAIL_DETAIL_FILES+=("$lf")
  return 1
}

_review_fail_logs() {
  local rep i
  if [ ${#FAIL_DETAIL_LABELS[@]} -eq 0 ] && [ ${#WARNINGS[@]} -eq 0 ] && [ ${#CRITICALS[@]} -eq 0 ]; then
    return 0
  fi
  _init_run_tmp
  rep="$(mktemp "$RUN_TMP/review.XXXXXX")"
  {
    if [ ${#CRITICALS[@]} -gt 0 ]; then
      printf '%s\n' "=== Errors ==="
      printf '%s\n' "${CRITICALS[@]}"
      printf '\n'
    fi
    if [ ${#WARNINGS[@]} -gt 0 ]; then
      printf '%s\n' "=== Warnings ==="
      printf '%s\n' "${WARNINGS[@]}"
      printf '\n'
    fi
    if [ ${#FAIL_DETAIL_LABELS[@]} -gt 0 ]; then
      printf '%s\n' "=== Last 10 lines per captured command ==="
      for i in "${!FAIL_DETAIL_LABELS[@]}"; do
        printf '\n--- %s ---\n' "${FAIL_DETAIL_LABELS[$i]}"
        tail -n 10 "${FAIL_DETAIL_FILES[$i]}" 2>/dev/null || printf '%s\n' "(no output)"
      done
    fi
  } >"$rep"
  echo ""
  if command -v less >/dev/null 2>&1; then
    echo -e "  ${DIM}Scrollable log: arrows / PgUp·PgDn · q closes${R}"
    less -R "$rep" || true
  else
    cat "$rep"
    read -r -s -p "  Press Enter..." _ || true
  fi
  rm -f "$rep"
}

log() { echo -e "  ${DIM}▸${R} $*"; }
ok()  { echo -e "  ${GR}${BOLD}✓${R} $*"; }
warn(){ echo -e "  ${YE}${BOLD}⚠${R} $*"; WARNINGS+=("$*"); }
err() { echo -e "  ${RE}${BOLD}✗${R} $*"; CRITICALS+=("$*"); }

phase_header() {
  local num="$1" title="$2"
  local iw=46 bar="" mid titlepad i
  clear_screen
  for ((i = 0; i < iw; i++)); do bar+="═"; done
  echo -e ""
  echo -e "  ${CY}${BOLD}╔${bar}╗${R}"
  mid="  NixOS Installer  |  Phase ${num} of 11"
  [ ${#mid} -gt "$iw" ] && mid="${mid:0:iw}"
  printf -v mid '%-*s' "$iw" "$mid"
  echo -e "  ${CY}${BOLD}║${R}${BOLD}${mid}${R}${CY}${BOLD}║${R}"
  echo -e "  ${CY}${BOLD}╠${bar}╣${R}"
  titlepad="  ${title}"
  [ ${#titlepad} -gt "$iw" ] && titlepad="${titlepad:0:iw}"
  printf -v titlepad '%-*s' "$iw" "$titlepad"
  echo -e "  ${CY}${BOLD}║${R}${BOLD}${titlepad}${R}${CY}${BOLD}║${R}"
  echo -e "  ${CY}${BOLD}╚${bar}╝${R}"
  echo -e ""
}

# ── TUI: arrow-key single-select ─────────────────────────────────────────────
tui_select() {
  local -n _result="$1"; shift
  local prompt="$1";     shift
  local items=("$@")
  local cur=0 total=${#items[@]} key esc

  hide_cursor
  echo -e "  ${BOLD}${prompt}${R}"
  echo -e "  ${DIM}(↑↓ select · Enter confirm)${R}"
  echo ""

  _render_list() {
    for i in "${!items[@]}"; do
      if [ "$i" -eq "$cur" ]; then
        echo -e "  ${CY}${BOLD}▶  ${items[$i]}${R}"
      else
        echo -e "     ${DIM}${items[$i]}${R}"
      fi
    done
  }

  printf '\033[s'
  _render_list

  while true; do
    IFS= read -r -s -n1 key
    if [ "$key" = $'\x1b' ]; then
      IFS= read -r -s -n1 esc
      IFS= read -r -s -n1 esc
      case "$esc" in
        A) if [ "$cur" -gt 0 ]; then cur=$(( cur - 1 )); fi ;;
        B) if [ "$cur" -lt $(( total - 1 )) ]; then cur=$(( cur + 1 )); fi ;;
      esac
    elif [ "$key" = "" ]; then
      break
    else
      continue
    fi
    printf '\033[u\033[0J'
    _render_list
  done

  printf '\033[u\033[0J'
  show_cursor
  echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}  ${CY}${items[$cur]}${R}"
  echo ""
  _result="${items[$cur]}"
}

# ── TUI: checkbox multi-select ────────────────────────────────────────────────
tui_checkbox() {
  local -n _checked="$1"; shift
  local prompt="$1";      shift
  local items=("$@")
  local cur=0 total=${#items[@]} key esc
  local selected=()
  for _ in "${items[@]}"; do selected+=(0); done

  hide_cursor
  echo -e "  ${BOLD}${prompt}${R}"
  echo -e "  ${DIM}(↑↓ navigate · Space toggle · Enter continue)${R}"
  echo ""

  _render_cb() {
    for i in "${!items[@]}"; do
      local box="[ ]" ocol="$DIM"
      [ "${selected[$i]}" -eq 1 ] && box="[${GR}x${R}]" && ocol=""
      if [ "$i" -eq "$cur" ]; then
        echo -e "  ${CY}${BOLD}▶${R}  ${box} ${BOLD}${items[$i]}${R}"
      else
        echo -e "     ${box} ${ocol}${items[$i]}${R}"
      fi
    done
  }

  printf '\033[s'
  _render_cb

  while true; do
    IFS= read -r -s -n1 key
    if [ "$key" = $'\x1b' ]; then
      IFS= read -r -s -n1 esc
      IFS= read -r -s -n1 esc
      case "$esc" in
        A) if [ "$cur" -gt 0 ]; then cur=$(( cur - 1 )); fi ;;
        B) if [ "$cur" -lt $(( total - 1 )) ]; then cur=$(( cur + 1 )); fi ;;
      esac
    elif [ "$key" = " " ]; then
      selected[$cur]=$(( 1 - selected[$cur] ))
    elif [ "$key" = "" ]; then
      break
    else
      continue
    fi
    printf '\033[u\033[0J'
    _render_cb
  done

  printf '\033[u\033[0J'
  show_cursor

  _checked=()
  for i in "${!items[@]}"; do
    [ "${selected[$i]}" -eq 1 ] && _checked+=("${items[$i]}")
  done

  if [ ${#_checked[@]} -gt 0 ]; then
    echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}"
    for item in "${_checked[@]}"; do echo -e "    ${CY}▸${R} ${item}"; done
  else
    echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}  ${DIM}(none — English only)${R}"
  fi
  echo ""
}

# ── TUI: text input ───────────────────────────────────────────────────────────
tui_input() {
  local -n _inp="$1"; shift
  local prompt="$1" default="${2:-}"
  printf '  '
  printf '%b' "${BOLD}"
  printf '%b' "$prompt"
  printf '%b' "${R}"
  if [ -n "$default" ]; then
    printf ' %b[%s]%b  ' "${DIM}" "$default" "${R}"
  else
    printf '  '
  fi
  IFS= read -r _inp
  [ -z "$_inp" ] && _inp="$default"
  echo ""
}

# ── TUI: masked password input ────────────────────────────────────────────────
tui_password() {
  local -n _pw="$1"; shift
  local prompt="$1" default="${2:-}"
  local _char _typed=""
  printf "  ${BOLD}%s${R} ${DIM}(hidden · enter = use default: %s)${R}  " "$prompt" "$default"
  while IFS= read -r -s -n1 _char; do
    if [ -z "$_char" ]; then
      break
    elif [ "$_char" = $'\x7f' ] || [ "$_char" = $'\b' ]; then
      if [ -n "$_typed" ]; then
        _typed="${_typed%?}"
        printf '\b \b'
      fi
    else
      _typed+="$_char"
      printf '*'
    fi
  done
  echo ""
  echo ""
  [ -z "$_typed" ] && _pw="$default" || _pw="$_typed"
}

# ── TUI: yes/no ───────────────────────────────────────────────────────────────
tui_yesno() {
  local -n _yn="$1"; shift
  local choice
  tui_select choice "$1" "Yes" "No"
  [ "$choice" = "Yes" ] && _yn=1 || _yn=0
}

# ═════════════════════════════════════════════════════════════════════════════
# Phase 0: Welcome
# ═════════════════════════════════════════════════════════════════════════════
phase_header "0" "Welcome"
echo -e "  This script will guide you through a full NixOS installation."
echo -e ""
echo -e "  ${YE}${BOLD}Requirements:${R}"
echo -e "    ${DIM}▸${R} Booted into a NixOS live ISO"
echo -e "    ${DIM}▸${R} Internet connection active"
echo -e "    ${DIM}▸${R} Target disk(s) visible under /dev/"
echo -e ""
read -r -s -p "  Press Enter to begin..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 1: System Identity
# ═════════════════════════════════════════════════════════════════════════════
phase_header "1" "System Identity"
echo -e "  Configure your username, config path, and login password."
echo ""

tui_input USERNAME "Username" "hogoshi"

_default_dest="/home/$USERNAME/nix-config"
tui_input DEST "Config path" "$_default_dest"

tui_password INIT_PASS "Initial password" "changeme"

echo -e "  ${GR}${BOLD}✓${R} Identity:"
echo -e "    ${DIM}▸${R} User:     ${CY}${USERNAME}${R}"
echo -e "    ${DIM}▸${R} Config:   ${CY}${DEST}${R}"
echo -e "    ${DIM}▸${R} Password: ${DIM}(set — hidden)${R}"
echo ""
read -r -s -p "  Press Enter to continue..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 2: Keyboard Layouts
# ═════════════════════════════════════════════════════════════════════════════
phase_header "2" "Keyboard Layouts"
echo -e "  ${GR}${BOLD}English (us)${R} is always included."
echo -e "  Select additional layouts. Cycle with ${CY}Alt+Shift${R}."
echo ""

_KB_OPTS=(
  "Russian    (ru)"
  "Spanish    (es)"
  "German     (de)"
  "French     (fr)"
  "Ukrainian  (ua)"
  "Polish     (pl)"
  "Japanese   (jp)"
  "Italian    (it)"
)

_KB_SELECTED=()
tui_checkbox _KB_SELECTED "Additional layouts:" "${_KB_OPTS[@]}"

KB_LAYOUT="us"
for _l in "${_KB_SELECTED[@]}"; do
  _code="${_l##*(}"
  _code="${_code%)}"
  _code="${_code// /}"
  KB_LAYOUT="${KB_LAYOUT},${_code}"
done

echo -e "  ${GR}${BOLD}✓${R} Active layout string:  ${CY}${BOLD}${KB_LAYOUT}${R}"
echo ""
read -r -s -p "  Press Enter to continue..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 3: Browser
# ═════════════════════════════════════════════════════════════════════════════
phase_header "3" "Browser"
echo -e "  Choose your default browser."
echo -e "  ${DIM}Zen Browser requires fetching from GitHub (github.com/youwen5/zen-browser-flake).${R}"
echo ""

tui_select BROWSER_CHOICE "Browser:" "Firefox" "Zen Browser"

# ═════════════════════════════════════════════════════════════════════════════
# Phase 4: Disks to Format
# ═════════════════════════════════════════════════════════════════════════════
phase_header "4" "Disks to Format"

mapfile -t ALL_DISKS < <(lsblk -dpno NAME,SIZE,MODEL \
  | grep -E '^/dev/(sd|nvme|vd)' \
  | awk '{printf "%s  (%s  %s)\n", $1, $2, $3}')

if [ ${#ALL_DISKS[@]} -eq 0 ]; then
  err "No disks detected. Is the system booted correctly?"
  show_cursor; exit 1
fi

FORMAT_DISKS=()
while [ ${#FORMAT_DISKS[@]} -eq 0 ]; do
  tui_checkbox FORMAT_DISKS "Select disks to format:" "${ALL_DISKS[@]}"
  if [ ${#FORMAT_DISKS[@]} -eq 0 ]; then
    warn "At least one disk must be selected."
  fi
done

# ═════════════════════════════════════════════════════════════════════════════
# Phase 5: Installation Disk
# ═════════════════════════════════════════════════════════════════════════════
phase_header "5" "Installation Disk"
echo -e "  ${DIM}Select which formatted disk NixOS will be installed on.${R}"
echo ""

PRIMARY_DISK=""
tui_select PRIMARY_DISK "Install NixOS on:" "${FORMAT_DISKS[@]}"
PRIMARY_DEV="${PRIMARY_DISK%% *}"

declare -A MOUNT_PATHS

for disk in "${FORMAT_DISKS[@]}"; do
  dev="${disk%% *}"
  [ "$dev" = "$PRIMARY_DEV" ] && continue
  mount_path=""
  tui_input mount_path "Mount path for ${CY}${dev}${R}:" "/hdd"
  MOUNT_PATHS["$dev"]="$mount_path"
done

# ═════════════════════════════════════════════════════════════════════════════
# Phase 6: Install Mode
# ═════════════════════════════════════════════════════════════════════════════
phase_header "6" "Install Mode"
echo -e "  ${BOLD}Auto${R}   — Script formats disk, runs nixos-install, sets everything up."
echo -e "  ${BOLD}Manual${R} — Script only writes config files; you run nixos-install yourself."
echo ""

INSTALL_MODE=""
tui_select INSTALL_MODE "How should NixOS be installed?" "Auto (fully automatic)" "Manual (I will run nixos-install myself)"

AUTO_INSTALL=0
[[ "$INSTALL_MODE" == Auto* ]] && AUTO_INSTALL=1

# ═════════════════════════════════════════════════════════════════════════════
# Phase 7: Write Nix configuration files
# ═════════════════════════════════════════════════════════════════════════════
phase_header "7" "Writing Configuration"

log "Creating ${DEST}..."
mkdir -p "$DEST"

log "Writing nix files..."
mkdir -p "$DEST"
cat > "$DEST/flake.nix" << 'NIX_EOF_flake_nix'
{
  description = "hogoshi's NixOS configuration";

  inputs = {
    millennium.url = "github:SteamClientHomebrew/Millennium?dir=packages/nix";

    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    spicetify-nix = {
      url = "github:Gerg-L/spicetify-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    zen-browser = {
      url = "github:youwen5/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ { self, nixpkgs, home-manager, spicetify-nix, ... }:
    let
      # true  = VPN only + minimal Hyprland (for initial setup behind Russia firewall)
      # false = full system (NVIDIA, apps, cachix, etc.)
      setupMode = true;

      # true = Zen Browser, false = Firefox
      useZen = false;

      system = "x86_64-linux";
    in {
      nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs setupMode useZen; };
        modules = [
          ./hosts/configuration.nix
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs    = true;
            home-manager.useUserPackages  = true;
            home-manager.extraSpecialArgs = { inherit inputs setupMode useZen; };
            home-manager.users.hogoshi    = import ./home;
          }
        ];
      };
    };
}
NIX_EOF_flake_nix

mkdir -p "$DEST/home"
cat > "$DEST/home/default.nix" << 'NIX_EOF_home_default_nix'
{ lib, setupMode, ... }: {
  imports = [
    ./programs/default.nix
  ] ++ lib.optionals (!setupMode) [
    ./programs/normal.nix
  ];

  home = {
    username      = "hogoshi";
    homeDirectory = "/home/hogoshi";
    stateVersion  = "24.11";
  };

  programs.home-manager.enable = true;
}
NIX_EOF_home_default_nix

mkdir -p "$DEST/home/programs/apps"
cat > "$DEST/home/programs/apps/default.nix" << 'NIX_EOF_home_programs_apps_default_nix'
{ pkgs, ... }: {
  home.packages = with pkgs; [
    htop
    git
    fastfetch
    kitty
  ];
}
NIX_EOF_home_programs_apps_default_nix

mkdir -p "$DEST/home/programs/apps"
cat > "$DEST/home/programs/apps/normal.nix" << 'NIX_EOF_home_programs_apps_normal_nix'
{ pkgs, ... }: {
  home.packages = with pkgs; [
    code-cursor
    telegram-desktop
    vesktop
    spotify
    pkgs.millennium-steam
  ];
}
NIX_EOF_home_programs_apps_normal_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/bash.nix" << 'NIX_EOF_home_programs_bash_nix'
{ pkgs, lib, useZen, setupMode, ... }:
{
  programs.bash = {
    enable = true;
    profileExtra = ''
      if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" = "1" ]; then
        exec start-hyprland
      fi
    '';
    shellAliases = {
      rr    = "sudo nixos-rebuild switch --flake /etc/nixos#nixos";
      clear = "clear && fastfetch";
    };
    initExtra = ''
      ${lib.optionalString setupMode ''
        printf '\n  Setup keybindings:\n'
        printf '  Super+Enter  —  kitty\n'
        printf '  Super+F      —  ${if useZen then "zen" else "firefox"}\n'
        printf '  Super+K      —  throne\n\n'
      ''}
      fastfetch
      PS1='\[\e[38;5;117m\]\u:\[\e[0m\]\w\[\e[38;5;117m\]$ \[\e[0m\]'

      ww() {
        local json="$HOME/.cache/matugen/colors.json"
        if [ ! -f "$json" ]; then
          echo "ww: no matugen colors found at $json"
          return 1
        fi

        local kitty_colors="$HOME/.config/kitty/colors.conf"
        mkdir -p "$(dirname "$kitty_colors")"
        ${pkgs.jq}/bin/jq -r '
          .colors.dark |
          "background           " + .surface,
          "foreground           " + .on_surface,
          "selection_background " + .primary,
          "selection_foreground " + .on_primary,
          "cursor               " + .primary,
          "cursor_text_color    " + .on_primary,
          "color0  " + .surface,
          "color1  " + .error,
          "color2  " + .tertiary,
          "color3  " + .secondary,
          "color4  " + .primary,
          "color5  " + .tertiary_container,
          "color6  " + .secondary_container,
          "color7  " + .on_surface,
          "color8  " + .outline,
          "color9  " + .error_container,
          "color10 " + .on_tertiary,
          "color11 " + .on_secondary,
          "color12 " + .on_primary,
          "color13 " + .on_tertiary_container,
          "color14 " + .on_secondary_container,
          "color15 " + .surface_variant
        ' "$json" > "$kitty_colors"

        if [ -n "$KITTY_PID" ]; then
          kitty @ set-colors --all --configured "$kitty_colors" 2>/dev/null || true
        fi

        ${lib.optionalString useZen ''
        local zen_profile
        zen_profile=$(find "$HOME/.zen" -maxdepth 1 -name "*.default*" -type d 2>/dev/null | head -1)
        [ -z "$zen_profile" ] && zen_profile=$(find "$HOME/.zen" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)
        if [ -n "$zen_profile" ]; then
          mkdir -p "$zen_profile/chrome"
          ${pkgs.jq}/bin/jq -r '
            .colors.dark |
            ":root {",
            "  --matugen-background: " + .surface + ";",
            "  --matugen-surface: " + .surface_variant + ";",
            "  --matugen-primary: " + .primary + ";",
            "  --matugen-on-primary: " + .on_primary + ";",
            "  --matugen-secondary: " + .secondary + ";",
            "  --matugen-on-surface: " + .on_surface + ";",
            "  --matugen-outline: " + .outline + ";",
            "  --matugen-error: " + .error + ";",
            "}"
          ' "$json" > "$zen_profile/chrome/matugen-vars.css"
        fi
        ''}
        ${lib.optionalString (!useZen) ''
        local ff_dir="$HOME/.mozilla/firefox/$USER/chrome"
        mkdir -p "$ff_dir"
        ${pkgs.jq}/bin/jq -r '
          .colors.dark |
          ":root {",
          "  --matugen-background: " + .surface + ";",
          "  --matugen-surface: " + .surface_variant + ";",
          "  --matugen-primary: " + .primary + ";",
          "  --matugen-on-primary: " + .on_primary + ";",
          "  --matugen-secondary: " + .secondary + ";",
          "  --matugen-on-surface: " + .on_surface + ";",
          "  --matugen-outline: " + .outline + ";",
          "  --matugen-error: " + .error + ";",
          "}"
        ' "$json" > "$ff_dir/matugen-vars.css"
        ''}

        local gtk_dir="$HOME/.config/gtk-3.0"
        mkdir -p "$gtk_dir"
        ${pkgs.jq}/bin/jq -r '
          .colors.dark |
          "@define-color accent_color " + .primary + ";",
          "@define-color accent_bg_color " + (.primary_container // .primary) + ";",
          "@define-color accent_fg_color " + .on_primary + ";",
          "@define-color destructive_color " + .error + ";",
          "@define-color window_bg_color " + .surface + ";",
          "@define-color window_fg_color " + .on_surface + ";",
          "@define-color view_bg_color " + .surface_variant + ";",
          "@define-color view_fg_color " + .on_surface + ";",
          "@define-color headerbar_bg_color " + .surface + ";",
          "@define-color headerbar_fg_color " + .on_surface + ";"
        ' "$json" > "$gtk_dir/gtk.css"

        echo "ww: colors synced from matugen"
      }
    '';
  };
}
NIX_EOF_home_programs_bash_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/default.nix" << 'NIX_EOF_home_programs_default_nix'
{ lib, useZen, ... }: {
  imports = [
    ./bash.nix
    ./apps
    ./hyprland.nix
  ] ++ (if useZen then [ ./zen.nix ] else [ ./firefox.nix ]);
}
NIX_EOF_home_programs_default_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/firefox.nix" << 'NIX_EOF_home_programs_firefox_nix'
{ pkgs, lib, setupMode, useZen, ... }: lib.mkIf (!useZen)
{
  programs.firefox = {
    enable = true;
    profiles.hogoshi = {
      isDefault = true;
      userChrome = lib.mkIf (!setupMode) (builtins.readFile ./firefox-userchrome-template.css);
    };
  };

  home.activation = lib.mkIf (!setupMode) {
    firefoxMatugenColors = {
      after  = [ "writeBoundary" ];
      before = [];
      data   = ''
        COLORS_JSON="$HOME/.cache/matugen/colors.json"
        PROFILE_DIR="$HOME/.mozilla/firefox/hogoshi"
        mkdir -p "$PROFILE_DIR/chrome"
        if [ -f "$COLORS_JSON" ]; then
          ${pkgs.jq}/bin/jq -r '
            .colors.dark |
            ":root {",
            "  --matugen-background: " + .surface + ";",
            "  --matugen-surface: " + .surface_variant + ";",
            "  --matugen-primary: " + .primary + ";",
            "  --matugen-on-primary: " + .on_primary + ";",
            "  --matugen-secondary: " + .secondary + ";",
            "  --matugen-on-surface: " + .on_surface + ";",
            "  --matugen-outline: " + .outline + ";",
            "  --matugen-error: " + .error + ";",
            "}"
          ' "$COLORS_JSON" > "$PROFILE_DIR/chrome/matugen-vars.css"
        else
          printf ':root {\n  --matugen-background: #1e1e2e;\n  --matugen-surface: #313244;\n  --matugen-primary: #89b4fa;\n  --matugen-on-primary: #1e1e2e;\n  --matugen-secondary: #cba6f7;\n  --matugen-on-surface: #cdd6f4;\n  --matugen-outline: #6c7086;\n  --matugen-error: #f38ba8;\n}\n' \
            > "$PROFILE_DIR/chrome/matugen-vars.css"
        fi
      '';
    };
  };
}
NIX_EOF_home_programs_firefox_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/hyprland.nix" << 'NIX_EOF_home_programs_hyprland_nix'
{ lib, setupMode, useZen, ... }:
{
  wayland.windowManager.hyprland = {
    enable = true;
    settings = {
      "$mod"      = "SUPER";
      "$terminal" = "kitty";
      exec-once   = [ "axctl" ];

      bind = [
        "$mod, Return, exec, $terminal"
        "$mod, Q, killactive"
      ] ++ lib.optionals setupMode [
        "$mod, F, exec, ${if useZen then "zen" else "firefox"}"
        "$mod, K, exec, throne"
      ];

      misc = {
        disable_hyprland_logo    = true;
        disable_splash_rendering = true;
      };

      general = {
        gaps_in   = 5;
        gaps_out  = 10;
        border_size = 2;
      };
    };
  };
}
NIX_EOF_home_programs_hyprland_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/kitty.nix" << 'NIX_EOF_home_programs_kitty_nix'
{ pkgs, ... }:
{
  programs.kitty = {
    enable = true;
    settings = {
      font_family      = "monospace";
      font_size        = 13;
      window_padding_width = 8;
      confirm_os_window_close = 0;
      include = "~/.config/kitty/colors.conf";
    };
  };

  home.activation.kittyMatugenColors = {
    after  = [ "writeBoundary" ];
    before = [];
    data   = ''
      COLORS_JSON="$HOME/.cache/matugen/colors.json"
      KITTY_COLORS="$HOME/.config/kitty/colors.conf"
      mkdir -p "$(dirname "$KITTY_COLORS")"
      if [ -f "$COLORS_JSON" ]; then
        ${pkgs.jq}/bin/jq -r '
          .colors.dark |
          "background           " + .surface,
          "foreground           " + .on_surface,
          "selection_background " + .primary,
          "selection_foreground " + .on_primary,
          "cursor               " + .primary,
          "cursor_text_color    " + .on_primary,
          "color0  " + .surface,
          "color1  " + .error,
          "color2  " + .tertiary,
          "color3  " + .secondary,
          "color4  " + .primary,
          "color5  " + .tertiary_container,
          "color6  " + .secondary_container,
          "color7  " + .on_surface,
          "color8  " + .outline,
          "color9  " + .error_container,
          "color10 " + .on_tertiary,
          "color11 " + .on_secondary,
          "color12 " + .on_primary,
          "color13 " + .on_tertiary_container,
          "color14 " + .on_secondary_container,
          "color15 " + .surface_variant
        ' "$COLORS_JSON" > "$KITTY_COLORS"
      else
        cat > "$KITTY_COLORS" << 'DEFAULTS'
background           #1e1e2e
foreground           #cdd6f4
cursor               #f5e0dc
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #f5c2e7
color6  #94e2d5
color7  #bac2de
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #a6adc8
DEFAULTS
      fi
    '';
  };
}
NIX_EOF_home_programs_kitty_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/normal.nix" << 'NIX_EOF_home_programs_normal_nix'
{ ... }: {
  imports = [
    ./apps/normal.nix
    ./kitty.nix
    ./spicetify.nix
  ];
}
NIX_EOF_home_programs_normal_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/spicetify.nix" << 'NIX_EOF_home_programs_spicetify_nix'
{ inputs, pkgs, ... }:

let
  spicePkgs = inputs.spicetify-nix.legacyPackages.${pkgs.system};
in
{
  imports = [ inputs.spicetify-nix.homeManagerModules.default ];

  programs.spicetify = {
    enable = true;
    theme  = spicePkgs.themes.comfy;
    colorScheme = "dark";

    enabledExtensions = with spicePkgs.extensions; [
      adblock
      hidePodcasts
    ];
  };

  home.activation.spicetifyMatugenColors = {
    after  = [ "writeBoundary" ];
    before = [];
    data   = ''
      COLORS_JSON="$HOME/.cache/matugen/colors.json"
      SPICETIFY_DIR="$HOME/.config/spicetify"
      mkdir -p "$SPICETIFY_DIR"
      if [ -f "$COLORS_JSON" ]; then
        ${pkgs.jq}/bin/jq -r '
          .colors.dark |
          "text=" + (.on_surface | ltrimstr("#")),
          "subtext=" + (.outline | ltrimstr("#")),
          "sidebar-text=" + (.on_surface | ltrimstr("#")),
          "main=" + (.surface | ltrimstr("#")),
          "sidebar=" + (.surface_variant | ltrimstr("#")),
          "player=" + (.surface | ltrimstr("#")),
          "card=" + (.surface_variant | ltrimstr("#")),
          "shadow=" + (.surface | ltrimstr("#")),
          "selected-row=" + (.primary_container | ltrimstr("#")),
          "button=" + (.primary | ltrimstr("#")),
          "button-active=" + (.on_primary | ltrimstr("#")),
          "button-disabled=" + (.outline | ltrimstr("#")),
          "tab-active=" + (.secondary_container | ltrimstr("#")),
          "notification=" + (.tertiary | ltrimstr("#")),
          "notification-error=" + (.error | ltrimstr("#")),
          "misc=" + (.outline | ltrimstr("#"))
        ' "$COLORS_JSON" > "$SPICETIFY_DIR/matugen-colors.ini"
      fi
    '';
  };
}
NIX_EOF_home_programs_spicetify_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/zen.nix" << 'NIX_EOF_home_programs_zen_nix'
{ pkgs, lib, setupMode, useZen, ... }: lib.mkIf (useZen && !setupMode) {
  home.activation.zenMatugenColors = {
    after  = [ "writeBoundary" ];
    before = [];
    data   = ''
      COLORS_JSON="$HOME/.cache/matugen/colors.json"
      ZEN_PROFILE=$(find "$HOME/.zen" -maxdepth 1 -name "*.default*" -type d 2>/dev/null | head -1)
      [ -z "$ZEN_PROFILE" ] && ZEN_PROFILE=$(find "$HOME/.zen" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | head -1)

      if [ -n "$ZEN_PROFILE" ]; then
        mkdir -p "$ZEN_PROFILE/chrome"
        if [ -f "$COLORS_JSON" ]; then
          ${pkgs.jq}/bin/jq -r '
            .colors.dark |
            ":root {",
            "  --matugen-background: " + .surface + ";",
            "  --matugen-surface: " + .surface_variant + ";",
            "  --matugen-primary: " + .primary + ";",
            "  --matugen-on-primary: " + .on_primary + ";",
            "  --matugen-secondary: " + .secondary + ";",
            "  --matugen-on-surface: " + .on_surface + ";",
            "  --matugen-outline: " + .outline + ";",
            "  --matugen-error: " + .error + ";",
            "}"
          ' "$COLORS_JSON" > "$ZEN_PROFILE/chrome/matugen-vars.css"
        else
          printf ':root {\n  --matugen-background: #1e1e2e;\n  --matugen-surface: #313244;\n  --matugen-primary: #89b4fa;\n  --matugen-on-primary: #1e1e2e;\n  --matugen-secondary: #cba6f7;\n  --matugen-on-surface: #cdd6f4;\n  --matugen-outline: #6c7086;\n  --matugen-error: #f38ba8;\n}\n' \
            > "$ZEN_PROFILE/chrome/matugen-vars.css"
        fi

        if [ ! -f "$ZEN_PROFILE/chrome/userChrome.css" ]; then
          printf '@import "matugen-vars.css";\n' > "$ZEN_PROFILE/chrome/userChrome.css"
        elif ! grep -q 'matugen-vars' "$ZEN_PROFILE/chrome/userChrome.css" 2>/dev/null; then
          printf '@import "matugen-vars.css";\n' >> "$ZEN_PROFILE/chrome/userChrome.css"
        fi
      fi
    '';
  };
}
NIX_EOF_home_programs_zen_nix

mkdir -p "$DEST/hosts"
cat > "$DEST/hosts/configuration.nix" << 'NIX_EOF_hosts_configuration_nix'
{ inputs, lib, setupMode, useZen, ... }: {
  imports = [
    ./hardware-configuration.nix
    ../modules/system/default.nix
    ../modules/desktop/default.nix
    ../modules/programs/throne.nix
  ] ++ lib.optionals (!setupMode) [
    ../modules/system/normal.nix
    ../modules/desktop/normal.nix
  ] ++ lib.optionals useZen [
    ../modules/programs/zen.nix
  ];

  nixpkgs.config.allowUnfree = true;
  nixpkgs.overlays = [ inputs.millennium.overlays.default ];

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    warn-dirty            = false;
  };

  system.stateVersion = "24.11";
}
NIX_EOF_hosts_configuration_nix

mkdir -p "$DEST/hosts"
cat > "$DEST/hosts/hardware-configuration.nix" << 'NIX_EOF_hosts_hardware_configuration_nix'
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9e71e9a6-7c51-49f5-907a-976511b258bb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1313-ACD5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/hdd" =
    { device = "/dev/disk/by-uuid/9e6a20a6-8f90-4a7b-b7aa-46869ef57a40";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
NIX_EOF_hosts_hardware_configuration_nix

mkdir -p "$DEST/modules/desktop"
cat > "$DEST/modules/desktop/cursor.nix" << 'NIX_EOF_modules_desktop_cursor_nix'
{ pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    bibata-cursors
  ];

  environment.sessionVariables = {
    XCURSOR_THEME = "Bibata-Modern-Classic";
    XCURSOR_SIZE  = "24";
  };
}
NIX_EOF_modules_desktop_cursor_nix

mkdir -p "$DEST/modules/desktop"
cat > "$DEST/modules/desktop/default.nix" << 'NIX_EOF_modules_desktop_default_nix'
{ ... }: {
  imports = [
    ./hyprland.nix
  ];
}
NIX_EOF_modules_desktop_default_nix

mkdir -p "$DEST/modules/desktop"
cat > "$DEST/modules/desktop/hyprland.nix" << 'NIX_EOF_modules_desktop_hyprland_nix'
{ pkgs, ... }: {
  services.getty.autologinUser = "hogoshi";

  programs.hyprland = {
    enable          = true;
    xwayland.enable = true;
  };

  xdg.portal = {
    enable       = true;
    extraPortals = [ pkgs.xdg-desktop-portal-hyprland ];
  };

  services.pipewire = {
    enable            = true;
    alsa.enable       = true;
    alsa.support32Bit = true;
    pulse.enable      = true;
  };
  services.pulseaudio.enable = false;

  environment.systemPackages = with pkgs; [
    wl-clipboard
    grim
    slurp
  ];
}
NIX_EOF_modules_desktop_hyprland_nix

mkdir -p "$DEST/modules/desktop"
cat > "$DEST/modules/desktop/normal.nix" << 'NIX_EOF_modules_desktop_normal_nix'
{ ... }: {
  imports = [
    ./cursor.nix
  ];
}
NIX_EOF_modules_desktop_normal_nix

mkdir -p "$DEST/modules/programs"
cat > "$DEST/modules/programs/throne.nix" << 'NIX_EOF_modules_programs_throne_nix'
{ pkgs, ...}: {
  programs.throne.enable = true;
  programs.throne.tunMode.enable = true;
}
NIX_EOF_modules_programs_throne_nix

mkdir -p "$DEST/modules/programs"
cat > "$DEST/modules/programs/zen.nix" << 'NIX_EOF_modules_programs_zen_nix'
{ inputs, pkgs, ... }: {
  environment.systemPackages = [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];
}
NIX_EOF_modules_programs_zen_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/boot.nix" << 'NIX_EOF_modules_system_boot_nix'
{ ... }:
{
  boot.loader = {
    systemd-boot = {
      enable = true;
      configurationLimit = 3;
    };
    efi.canTouchEfiVariables = true;
  };
}
NIX_EOF_modules_system_boot_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/cachix.nix" << 'NIX_EOF_modules_system_cachix_nix'
{ ... }: {
  nix.settings = {
    substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"
      "https://nixpkgs-wayland.cachix.org"
      "https://hyprland.cachix.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCUSeBs="
      "nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StdjkXTx/dABGUj7PBKuEwP9Pg="
      "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="
    ];
  };
}
NIX_EOF_modules_system_cachix_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/default.nix" << 'NIX_EOF_modules_system_default_nix'
{ ... }: {
  imports = [
    ./boot.nix
    ./networking.nix
    ./locale.nix
    ./users.nix
    ./zram.nix
    ./cachix.nix
  ];
}
NIX_EOF_modules_system_default_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/graphics.nix" << 'NIX_EOF_modules_system_graphics_nix'
{ config, pkgs, ... }:
{
  hardware.nvidia = {
    modesetting.enable          = true;
    powerManagement.enable      = false;
    powerManagement.finegrained = false;
    open                        = false;
    nvidiaSettings              = true;
    package                     = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  hardware.graphics = {
    enable      = true;
    enable32Bit = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  boot.initrd.kernelModules = [ "nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm" ];

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME      = "nvidia";
    XDG_SESSION_TYPE       = "wayland";
    GBM_BACKEND            = "nvidia-drm";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    WLR_NO_HARDWARE_CURSORS = "1";
    NIXOS_OZONE_WL         = "1";
  };
}
NIX_EOF_modules_system_graphics_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/locale.nix" << 'NIX_EOF_modules_system_locale_nix'
{ ... }:
{
  time.timeZone = "Asia/Krasnoyarsk";

  i18n = {
    defaultLocale = "en_US.UTF-8";
    extraLocaleSettings = {
      LC_ADDRESS        = "en_US.UTF-8";
      LC_IDENTIFICATION = "en_US.UTF-8";
      LC_MEASUREMENT    = "en_US.UTF-8";
      LC_MONETARY       = "en_US.UTF-8";
      LC_NAME           = "en_US.UTF-8";
      LC_NUMERIC        = "en_US.UTF-8";
      LC_PAPER          = "en_US.UTF-8";
      LC_TELEPHONE      = "en_US.UTF-8";
      LC_TIME           = "en_US.UTF-8";
    };
  };
}
NIX_EOF_modules_system_locale_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/networking.nix" << 'NIX_EOF_modules_system_networking_nix'
{ ... }:
{
  networking = {
    hostName = "nixos";
    networkmanager.enable = true;
    firewall.checkReversePath = "loose";
  };
}
NIX_EOF_modules_system_networking_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/normal.nix" << 'NIX_EOF_modules_system_normal_nix'
{ ... }: {
  imports = [
    ./graphics.nix
  ];
}
NIX_EOF_modules_system_normal_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/users.nix" << 'NIX_EOF_modules_system_users_nix'
{ pkgs, ... }:
{
  users.users.hogoshi = {
    isNormalUser = true;
    description  = "hogoshi";
    extraGroups  = [ "networkmanager" "wheel" "video" "audio" ];
    shell        = pkgs.bash;
    initialPassword = "changeme";
  };
}
NIX_EOF_modules_system_users_nix

mkdir -p "$DEST/modules/system"
cat > "$DEST/modules/system/zram.nix" << 'NIX_EOF_modules_system_zram_nix'
{ ... }:
{
  # zram swap instead of a swap partition (4GB out of 16GB RAM)
  zramSwap = {
    enable        = true;
    memoryPercent = 25;
  };
}
NIX_EOF_modules_system_zram_nix

mkdir -p "$DEST/home/programs"
cat > "$DEST/home/programs/firefox-userchrome-template.css" << 'EXTRA_EOF_home_programs_firefox_userchrome_template_css'
@import "matugen-vars.css";

:root {
  --toolbar-bgcolor: var(--matugen-background, #1e1e2e) !important;
  --toolbar-color: var(--matugen-on-surface, #cdd6f4) !important;
  --toolbarbutton-hover-background: var(--matugen-surface, #313244) !important;
  --toolbarbutton-active-background: var(--matugen-primary, #89b4fa) !important;
  --tab-selected-bgcolor: var(--matugen-surface, #313244) !important;
  --urlbar-background: var(--matugen-surface, #313244) !important;
}

#navigator-toolbox {
  background-color: var(--matugen-background, #1e1e2e) !important;
  border-bottom: 1px solid var(--matugen-outline, #6c7086) !important;
}

.tab-background:is([selected], [multiselected]) {
  background-color: var(--matugen-surface, #313244) !important;
}

#urlbar-background {
  background-color: var(--matugen-surface, #313244) !important;
  border-color: var(--matugen-outline, #6c7086) !important;
}

#urlbar:focus-within #urlbar-background {
  border-color: var(--matugen-primary, #89b4fa) !important;
}
EXTRA_EOF_home_programs_firefox_userchrome_template_css


log "Patching config for user: ${USERNAME}..."
find "$DEST" -name "*.nix" -print0 \
  | xargs -0 sed -i "s|hogoshi|${USERNAME}|g"
sed -i "s|initialPassword = \"[^\"]*\"|initialPassword = \"${INIT_PASS}\"|" \
  "$DEST/modules/system/users.nix"
if [ "$BROWSER_CHOICE" = "Zen Browser" ]; then
  sed -i "s|useZen = false|useZen = true|" "$DEST/flake.nix"
  log "Browser: Zen Browser (useZen = true)"
else
  log "Browser: Firefox (useZen = false)"
fi
if [ -f "$DEST/flake.lock" ]; then
  log "Removing flake.lock — sed/username edits change sources; locked self narHash would abort nixos-install."
  rm -f "$DEST/flake.lock"
fi
ok "Config patched."

log "Making ${DEST} readable/writable for all (no chown)..."
chmod -R a+rwX "$DEST" 2>/dev/null || warn "chmod a+rwX on ${DEST} incomplete (try as root if needed)"

log "Linking /etc/nixos → ${DEST}..."
if _capt "sudo ln /etc/nixos → ${DEST}" bash -c "sudo rm -rf /etc/nixos && sudo ln -sf \"$DEST\" /etc/nixos"; then
  ok "/etc/nixos linked."
else
  warn "Could not link /etc/nixos — do it manually: sudo ln -sf ${DEST} /etc/nixos"
fi

ok "Configuration written."

# ═════════════════════════════════════════════════════════════════════════════
# Phase 8: Disk Formatting
# ═════════════════════════════════════════════════════════════════════════════
phase_header "8" "Disk Formatting"

if [ -z "$PRIMARY_DEV" ]; then
  err "Installation disk was not selected."
  AUTO_INSTALL=0
fi

if [ "$AUTO_INSTALL" -eq 0 ]; then
  echo -e "  ${DIM}Manual mode — skipping disk formatting.${R}"
  echo ""
  if [ -n "$PRIMARY_DEV" ]; then
    echo -e "  Format ${CY}${PRIMARY_DEV}${R} yourself, then:"
  else
    echo -e "  Select and format your installation disk yourself, then:"
  fi
  echo -e "    ${BOLD}sudo nixos-generate-config --root /mnt${R}"
  echo -e "  ${DIM}With root on /mnt, copy your repo to /mnt/etc/nixos, then lock and install:${R}"
  echo -e "    ${BOLD}sudo cp -a /path/to/your-flake/. /mnt/etc/nixos/${R}"
  echo -e "    ${BOLD}sudo nix --extra-experimental-features 'nix-command flakes' flake lock /mnt/etc/nixos${R}"
  echo -e "    ${BOLD}sudo nixos-install --flake /mnt/etc/nixos#nixos${R}"
  echo -e "  ${DIM}(Using /home/... via /etc/nixos can trigger Nix flake narHash / store-path assertions.)${R}"
  read -r -s -p "  Press Enter to continue..." _
  echo ""
else
  echo -e "  ${YE}${BOLD}WARNING:${R} All data on ${CY}${BOLD}${PRIMARY_DEV}${R} will be destroyed."
  echo ""
  read -r -s -p "  Press Enter to confirm and begin formatting..." _
  echo ""

  log "Partitioning ${PRIMARY_DEV}..."
  if _capt "parted ${PRIMARY_DEV}" sudo parted -s "$PRIMARY_DEV" -- \
      mklabel gpt \
      mkpart ESP fat32 1MiB 512MiB \
      set 1 esp on \
      mkpart primary ext4 512MiB 100%; then
    ok "Partition table created."
  else
    err "Partitioning failed on ${PRIMARY_DEV}."
  fi

  if [[ "$PRIMARY_DEV" == *nvme* ]]; then
    BOOT_PART="${PRIMARY_DEV}p1"
    ROOT_PART="${PRIMARY_DEV}p2"
  else
    BOOT_PART="${PRIMARY_DEV}1"
    ROOT_PART="${PRIMARY_DEV}2"
  fi

  log "Formatting boot partition (FAT32)..."
  if _capt "mkfs.fat ${BOOT_PART}" sudo mkfs.fat -F 32 -n BOOT "$BOOT_PART"; then
    ok "Boot: ${BOOT_PART}"
  else
    warn "mkfs.fat failed on ${BOOT_PART}"
  fi

  log "Formatting root partition (ext4)..."
  if _capt "mkfs.ext4 ${ROOT_PART}" sudo mkfs.ext4 -L nixos "$ROOT_PART"; then
    ok "Root: ${ROOT_PART}"
  else
    warn "mkfs.ext4 failed on ${ROOT_PART}"
  fi

  log "Mounting root..."
  if _capt "mount ${ROOT_PART} /mnt" sudo mount "$ROOT_PART" /mnt; then
    ok "Mounted ${ROOT_PART} → /mnt"
  else
    err "Mount failed for ${ROOT_PART}"
  fi

  sudo mkdir -p /mnt/boot
  if _capt "mount ${BOOT_PART} /mnt/boot" sudo mount "$BOOT_PART" /mnt/boot; then
    ok "Mounted ${BOOT_PART} → /mnt/boot"
  else
    warn "Boot mount failed for ${BOOT_PART}"
  fi

  for dev in "${!MOUNT_PATHS[@]}"; do
    mpath="${MOUNT_PATHS[$dev]}"
    log "Formatting extra disk ${dev} (ext4)..."
    if _capt "mkfs.ext4 ${dev}" sudo mkfs.ext4 -L "$(basename "$mpath")" "$dev"; then
      ok "Formatted: ${dev}"
    else
      warn "mkfs.ext4 failed on ${dev}"
    fi
    sudo mkdir -p "/mnt${mpath}"
    if _capt "mount ${dev} → /mnt${mpath}" sudo mount "$dev" "/mnt${mpath}"; then
      ok "Mounted ${dev} → /mnt${mpath}"
    else
      warn "Could not mount ${dev} → /mnt${mpath}"
    fi
  done

  log "Generating hardware config..."
  if _capt "nixos-generate-config --root /mnt" sudo nixos-generate-config --root /mnt; then
    ok "hardware-configuration.nix generated."
  else
    warn "nixos-generate-config failed — hardware config may be incomplete"
  fi

  GENERATED_HW="/mnt/etc/nixos/hardware-configuration.nix"
  if [ -f "$GENERATED_HW" ]; then
    cp "$GENERATED_HW" "$DEST/hosts/hardware-configuration.nix"
    ok "Copied hardware config to repo."
  else
    warn "Could not find generated hardware-configuration.nix at ${GENERATED_HW}"
  fi
fi

# ═════════════════════════════════════════════════════════════════════════════
# Phase 9: NixOS Installation
# ═════════════════════════════════════════════════════════════════════════════
phase_header "9" "NixOS Installation"

if [ "$AUTO_INSTALL" -eq 0 ]; then
  echo -e "  ${DIM}Manual mode — skipping nixos-install.${R}"
  echo ""
  echo -e "  ${DIM}Copy your flake to /mnt/etc/nixos, then lock and install (avoids Nix flake.cc narHash assert):${R}"
  echo -e "    ${BOLD}sudo nix --extra-experimental-features 'nix-command flakes' flake lock /mnt/etc/nixos${R}"
  echo -e "    ${CY}${BOLD}sudo nixos-install --flake /mnt/etc/nixos#nixos${R}"
  echo -e "  ${DIM}Avoid /etc/nixos → /home/... when installing: Nix can abort on flake self narHash vs store path.${R}"
  read -r -s -p "  Press Enter to continue..." _
  echo ""
else
  log "Installing flake onto /mnt/etc/nixos (avoids /home + /etc/nixos symlink flake store assertions)..."
  sudo rm -rf /mnt/etc/nixos
  sudo mkdir -p /mnt/etc/nixos
  sudo cp -a "${DEST}/." /mnt/etc/nixos/
  sudo rm -f /mnt/etc/nixos/flake.lock
  sudo chmod -R a+rwX /mnt/etc/nixos 2>/dev/null || true
  log "Pointing live /etc/nixos → /mnt/etc/nixos so flake path matches target root..."
  if _capt "ln /etc/nixos → /mnt/etc/nixos" sudo ln -sfn /mnt/etc/nixos /etc/nixos; then
    ok "/etc/nixos → /mnt/etc/nixos"
  else
    warn "Could not relink /etc/nixos; install still uses /mnt/etc/nixos#nixos"
  fi
  log "Locking flake on target (fresh flake.lock; needs nix-command + flakes for root nix)..."
  if _capt "nix flake lock /mnt/etc/nixos" sudo nix --extra-experimental-features 'nix-command flakes' flake lock /mnt/etc/nixos; then
    ok "flake.lock written under /mnt/etc/nixos"
  else
    warn "nix flake lock failed (root nix needs flakes features, or network); nixos-install may still hit Nix flake.cc assertion"
  fi
  log "Running nixos-install..."
  echo ""
  _init_run_tmp
  _nil="$(mktemp "$RUN_TMP/nixinst.XXXXXX")"
  set +e
  set +o pipefail
  sudo nixos-install --no-root-passwd --flake /mnt/etc/nixos#nixos 2>&1 | tee "$_nil"
  _nix_ec=${PIPESTATUS[0]}
  set -o pipefail
  set -e
  if [ "$_nix_ec" -eq 0 ]; then
    rm -f "$_nil"
    ok "NixOS installed successfully."
    INSTALL_OK=1
  else
    err "nixos-install failed — captured output can be reviewed below."
    FAIL_DETAIL_LABELS+=("nixos-install")
    FAIL_DETAIL_FILES+=("$_nil")
  fi
fi

if [ "$AUTO_INSTALL" -eq 1 ] && [ "$INSTALL_OK" -eq 1 ]; then
phase_header "10" "Dotfiles & Assets"
log "Linking asset files..."
TARGET_ROOT="/mnt"
TARGET_CONFIG="/mnt/etc/nixos"
RUNTIME_CONFIG="/etc/nixos"
mkdir -p "$TARGET_CONFIG/assets"
cat > "$TARGET_CONFIG/assets/fastfetch.json" << 'ASSET_EOF_fastfetch_json_'
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "builtin",
    "source": "nixos_small",
    "color": {
      "1": "blue",
      "2": "cyan"
    }
  },
  "display": {
    "separator": "  ",
    "color": {
      "keys": "blue",
      "title": "blue",
      "separator": "cyan"
    }
  },
  "modules": [
    "title",
    "separator",
    "os",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "display",
    "de",
    "wm",
    "terminal",
    "cpu",
    "gpu",
    "memory",
    "disk",
    "separator",
    "colors"
  ]
}
ASSET_EOF_fastfetch_json_
_apath="/home/hogoshi/.config/fastfetch/config.json"
_apath="${_apath//hogoshi/$USERNAME}"
_target_apath="${TARGET_ROOT}${_apath}"
mkdir -p "$(dirname "$_target_apath")"
ln -sf "$RUNTIME_CONFIG/assets/fastfetch.json" "$_target_apath"
log "  linked: assets/fastfetch.json"

cat > "$TARGET_CONFIG/assets/hyprland.conf" << 'ASSET_EOF_hyprland_conf_'
source = ~/.local/share/ambxst/hyprland.conf

monitor = ,3440x1440@180,0x0,1

input {
    kb_layout = us
    kb_options = grp:alt_shift_toggle
}

misc {
    disable_autoreload = false
}
ASSET_EOF_hyprland_conf_
sed -i "s|kb_layout = .*|kb_layout = ${KB_LAYOUT}|" "$TARGET_CONFIG/assets/hyprland.conf"
log "  kb_layout → ${KB_LAYOUT}"
_apath="/home/hogoshi/.config/hypr/hyprland.conf"
_apath="${_apath//hogoshi/$USERNAME}"
_target_apath="${TARGET_ROOT}${_apath}"
mkdir -p "$(dirname "$_target_apath")"
ln -sf "$RUNTIME_CONFIG/assets/hyprland.conf" "$_target_apath"
log "  linked: assets/hyprland.conf"

fi

# ═════════════════════════════════════════════════════════════════════════════
# Phase 11: Done
# ═════════════════════════════════════════════════════════════════════════════
phase_header "11" "Complete"

nw=${#WARNINGS[@]}
nc=${#CRITICALS[@]}
nd=${#FAIL_DETAIL_LABELS[@]}

if [ "$nw" -eq 0 ] && [ "$nc" -eq 0 ]; then
  echo -e "  ${GR}${BOLD}All phases completed without errors.${R}"
else
  if [ "$nc" -gt 0 ]; then
    echo -e "  ${RE}${BOLD}Errors (${nc}):${R}"
    for e in "${CRITICALS[@]}"; do echo -e "    ${RE}▸${R} ${e}"; done
    echo ""
  fi
  if [ "$nw" -gt 0 ]; then
    echo -e "  ${YE}${BOLD}Warnings (${nw}):${R}"
    for e in "${WARNINGS[@]}"; do echo -e "    ${YE}▸${R} ${e}"; done
    echo ""
  fi
fi

echo ""
echo -e "  ${BOLD}Summary:${R}"
echo -e "    ${DIM}▸${R} User:     ${CY}${USERNAME}${R}"
if [ "$AUTO_INSTALL" -eq 1 ]; then
  echo -e "    ${DIM}▸${R} Config:   ${CY}/etc/nixos${R}"
else
  echo -e "    ${DIM}▸${R} Config:   ${CY}${DEST}${R}"
fi
echo -e "    ${DIM}▸${R} Keyboard: ${CY}${KB_LAYOUT}${R}"
echo -e "    ${DIM}▸${R} Browser:  ${CY}${BROWSER_CHOICE}${R}"
echo ""
if [ "$AUTO_INSTALL" -eq 0 ]; then
  echo -e "  ${BOLD}Manual next steps:${R}"
  echo -e "    ${DIM}1.${R} ${CY}sudo cp -a \"${DEST}/.\" /mnt/etc/nixos/${R}  ${DIM}·${R}  ${CY}sudo nix --extra-experimental-features 'nix-command flakes' flake lock /mnt/etc/nixos${R}"
  echo -e "    ${DIM}2.${R} ${CY}sudo nixos-install --flake /mnt/etc/nixos#nixos${R}"
  echo -e "    ${DIM}3.${R} Reboot:   ${CY}reboot${R}"
  echo -e "    ${DIM}4.${R} Login as: ${CY}${USERNAME}${R}  (password: ${CY}${INIT_PASS}${R})"
  echo -e "    ${DIM}5.${R} Set up VPN, edit flake → ${CY}setupMode = false${R}, run ${CY}rr${R}"
elif [ "$INSTALL_OK" -eq 1 ] && [ "$nw" -eq 0 ] && [ "$nc" -eq 0 ]; then
  echo -e "  ${GR}${BOLD}Auto install completed successfully.${R}"
  echo -e "  ${DIM}Rebooting in 5 seconds.${R}"
  sleep 5
  sudo reboot
else
  echo -e "  ${YE}${BOLD}Auto install did not finish cleanly. Reboot is not started.${R}"
fi
echo ""
if [ "$nw" -gt 0 ] || [ "$nc" -gt 0 ] || [ "$nd" -gt 0 ]; then
  _review_fail_logs
fi
