# --- AMBXST THEME ---
# source = ~/.local/share/ambxst/hyprland.conf
# monitor = ,3440x1440@180,0x0,1

# --- SETUP MODE BINDS ---
$mod = SUPER
$terminal = kitty
exec-once = axctl
bind = $mod, Return, exec, $terminal
bind = $mod, Q, killactive
bind = $mod, F, exec, firefox
bind = $mod, K, exec, throne
# ------------------------

input {
    kb_layout = us
    kb_options = grp:alt_shift_toggle
}

misc {
    disable_autoreload = false
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}
