#!/usr/bin/env bash
# Builds setup-nixos.sh from the current nix-config repo.
# Run from the repo root: bash scripts/build-installer.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/setup-nixos.sh"

# ── Builder UI ────────────────────────────────────────────────────────────────

C_RESET='\033[0m'
C_BOLD='\033[1m'
C_CYAN='\033[36m'
C_GREEN='\033[32m'
C_DIM='\033[2m'

builder_header() {
  echo -e ""
  echo -e "${C_CYAN}${C_BOLD}  ╔══════════════════════════════════════════╗${C_RESET}"
  echo -e "${C_CYAN}${C_BOLD}  ║        NixOS Installer Builder           ║${C_RESET}"
  echo -e "${C_CYAN}${C_BOLD}  ╚══════════════════════════════════════════╝${C_RESET}"
  echo -e ""
}

builder_step() { echo -e "  ${C_CYAN}▶${C_RESET} ${C_BOLD}$1${C_RESET}"; }
builder_ok()   { echo -e "  ${C_GREEN}✓${C_RESET} $1"; }

# ── Nix file embedding ────────────────────────────────────────────────────────
# All paths use $DEST as a RUNTIME variable (not expanded at build time).

emit_nix_file() {
  local rel="$1"
  local abs="$REPO_ROOT/$rel"
  local content
  content="$(cat "$abs")"

  if [ "$rel" = "flake.nix" ]; then
    content="${content/setupMode = false/setupMode = true}"
  fi

  local delim="NIX_EOF_${rel//[^A-Za-z0-9]/_}"
  local dir
  dir="$(dirname "$rel")"

  if [ "$dir" = "." ]; then
    printf 'mkdir -p "$DEST"\n'
  else
    printf 'mkdir -p "$DEST/%s"\n' "$dir"
  fi
  printf 'cat > "$DEST/%s" << '"'"'%s'"'"'\n' "$rel" "$delim"
  printf '%s\n' "$content"
  printf '%s\n\n' "$delim"
}

emit_extra_file() {
  local rel="$1"
  local abs="$REPO_ROOT/$rel"
  [ -f "$abs" ] || return 0
  local delim="EXTRA_EOF_${rel//[^A-Za-z0-9]/_}"
  local dir
  dir="$(dirname "$rel")"

  printf 'mkdir -p "$DEST/%s"\n' "$dir"
  printf 'cat > "$DEST/%s" << '"'"'%s'"'"'\n' "$rel" "$delim"
  cat "$abs"
  printf '%s\n\n' "$delim"
}

# ── Asset embedding ───────────────────────────────────────────────────────────
# For hyprland.conf: patches kb_layout with $KB_LAYOUT after writing.
# All dest paths substitute USERNAME at runtime.

emit_asset_links() {
  local assets_dir="$REPO_ROOT/assets"
  [ -d "$assets_dir" ] || return 0

  cat << 'ASSET_PHASE_HDR'
phase_header "10" "Dotfiles & Assets"
log "Linking asset files..."
mkdir -p "$DEST/assets"
ASSET_PHASE_HDR

  for path_file in "$assets_dir"/*.path; do
    [ -f "$path_file" ] || continue
    local base="${path_file%.path}"
    [ -f "$base" ] || continue

    local orig_dest
    orig_dest="$(tr -d '[:space:]' < "$path_file")"
    local rel_src="assets/$(basename "$base")"
    local delim="ASSET_EOF_$(basename "$base" | tr -c 'A-Za-z0-9' '_')"

    printf 'cat > "$DEST/%s" << '"'"'%s'"'"'\n' "$rel_src" "$delim"
    cat "$base"
    printf '%s\n' "$delim"

    if [ "$(basename "$base")" = "hyprland.conf" ]; then
      printf 'sed -i "s|kb_layout = .*|kb_layout = ${KB_LAYOUT}|" "$DEST/%s"\n' "$rel_src"
      printf 'log "  kb_layout → ${KB_LAYOUT}"\n'
    fi

    printf '_apath="%s"\n' "$orig_dest"
    printf '_apath="${_apath//hogoshi/$USERNAME}"\n'
    printf 'mkdir -p "$(dirname "$_apath")"\n'
    printf 'ln -sf "$DEST/%s" "$_apath"\n' "$rel_src"
    printf 'log "  linked: %s"\n\n' "$rel_src"
  done
}

# ── Generated setup-nixos.sh ─────────────────────────────────────────────────

emit_setup_script() {
cat << 'SETUP_HEADER'
#!/usr/bin/env bash
# Generated by scripts/build-installer.sh — do not edit directly.
# Run on a fresh NixOS live ISO to bootstrap the system.
set -euo pipefail

DEST=""
USERNAME=""
INIT_PASS=""
KB_LAYOUT="us"
BROWSER_CHOICE=""
ERRORS=()

# ── Colors & TUI ─────────────────────────────────────────────────────────────

R='\033[0m'
BOLD='\033[1m'
DIM='\033[2m'
CY='\033[36m'
GR='\033[32m'
YE='\033[33m'
RE='\033[31m'

hide_cursor()  { printf '\033[?25l'; }
show_cursor()  { printf '\033[?25h'; }
clear_screen() { printf '\033[2J\033[H'; }

trap 'show_cursor' EXIT

_abort_install() {
  show_cursor
  clear_screen
  printf '%s\n' "Aborting installation..."
  trap - INT TERM
  exit 130
}
trap '_abort_install' INT TERM

log() { echo -e "  ${DIM}▸${R} $*"; }
ok()  { echo -e "  ${GR}${BOLD}✓${R} $*"; }
warn(){ echo -e "  ${YE}${BOLD}⚠${R} $*"; ERRORS+=("$*"); }
err() { echo -e "  ${RE}${BOLD}✗${R} $*"; ERRORS+=("CRITICAL: $*"); }

phase_header() {
  local num="$1" title="$2"
  clear_screen
  echo -e ""
  echo -e "  ${CY}${BOLD}╔══════════════════════════════════════════════╗${R}"
  printf   "  ${CY}${BOLD}║${R}  ${BOLD}NixOS Installer${R}  ${DIM}│${R}  Phase %-2s of 11        ${CY}${BOLD}║${R}\n" "$num"
  echo -e "  ${CY}${BOLD}╠══════════════════════════════════════════════╣${R}"
  printf   "  ${CY}${BOLD}║${R}  ${BOLD}%-44s${R}${CY}${BOLD}║${R}\n" "$title"
  echo -e "  ${CY}${BOLD}╚══════════════════════════════════════════════╝${R}"
  echo -e ""
}

# ── TUI: arrow-key single-select ─────────────────────────────────────────────
tui_select() {
  local -n _result="$1"; shift
  local prompt="$1";     shift
  local items=("$@")
  local cur=0 total=${#items[@]} key esc

  hide_cursor
  echo -e "  ${BOLD}${prompt}${R}"
  echo -e "  ${DIM}(↑↓ select · Enter confirm)${R}"
  echo ""

  _render_list() {
    for i in "${!items[@]}"; do
      if [ "$i" -eq "$cur" ]; then
        echo -e "  ${CY}${BOLD}▶  ${items[$i]}${R}"
      else
        echo -e "     ${DIM}${items[$i]}${R}"
      fi
    done
  }

  printf '\033[s'
  _render_list

  while true; do
    IFS= read -r -s -n1 key
    if [ "$key" = $'\x1b' ]; then
      IFS= read -r -s -n1 esc
      IFS= read -r -s -n1 esc
      case "$esc" in
        A) [ "$cur" -gt 0 ] && (( cur-- )) ;;
        B) [ "$cur" -lt $(( total - 1 )) ] && (( cur++ )) ;;
      esac
    elif [ "$key" = "" ]; then
      break
    else
      continue
    fi
    printf '\033[u\033[0J'
    _render_list
  done

  printf '\033[u\033[0J'
  show_cursor
  echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}  ${CY}${items[$cur]}${R}"
  echo ""
  _result="${items[$cur]}"
}

# ── TUI: checkbox multi-select ────────────────────────────────────────────────
tui_checkbox() {
  local -n _checked="$1"; shift
  local prompt="$1";      shift
  local items=("$@")
  local cur=0 total=${#items[@]} key esc
  local selected=()
  for _ in "${items[@]}"; do selected+=(0); done

  hide_cursor
  echo -e "  ${BOLD}${prompt}${R}"
  echo -e "  ${DIM}(↑↓ navigate · Space toggle · Enter continue)${R}"
  echo ""

  _render_cb() {
    for i in "${!items[@]}"; do
      local box="[ ]" col="$DIM"
      [ "${selected[$i]}" -eq 1 ] && box="[${GR}x${R}]" && col=""
      if [ "$i" -eq "$cur" ]; then
        echo -e "  ${CY}${BOLD}▶${R}  ${box} ${col}${items[$i]}${R}"
      else
        echo -e "     ${box} ${col}${DIM}${items[$i]}${R}"
      fi
    done
  }

  printf '\033[s'
  _render_cb

  while true; do
    IFS= read -r -s -n1 key
    if [ "$key" = $'\x1b' ]; then
      IFS= read -r -s -n1 esc
      IFS= read -r -s -n1 esc
      case "$esc" in
        A) [ "$cur" -gt 0 ] && (( cur-- )) ;;
        B) [ "$cur" -lt $(( total - 1 )) ] && (( cur++ )) ;;
      esac
    elif [ "$key" = " " ]; then
      selected[$cur]=$(( 1 - selected[$cur] ))
    elif [ "$key" = "" ]; then
      break
    else
      continue
    fi
    printf '\033[u\033[0J'
    _render_cb
  done

  printf '\033[u\033[0J'
  show_cursor

  _checked=()
  for i in "${!items[@]}"; do
    [ "${selected[$i]}" -eq 1 ] && _checked+=("${items[$i]}")
  done

  if [ ${#_checked[@]} -gt 0 ]; then
    echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}"
    for item in "${_checked[@]}"; do echo -e "    ${CY}▸${R} ${item}"; done
  else
    echo -e "  ${GR}${BOLD}✓${R} ${BOLD}${prompt}${R}  ${DIM}(none — English only)${R}"
  fi
  echo ""
}

# ── TUI: text input ───────────────────────────────────────────────────────────
tui_input() {
  local -n _inp="$1"; shift
  local prompt="$1" default="${2:-}"
  local hint=""
  [ -n "$default" ] && hint=" ${DIM}[${default}]${R}"
  printf "  ${BOLD}%s${R}%b  " "$prompt" "$hint"
  IFS= read -r _inp
  [ -z "$_inp" ] && _inp="$default"
  echo ""
}

# ── TUI: masked password input ────────────────────────────────────────────────
tui_password() {
  local -n _pw="$1"; shift
  local prompt="$1" default="${2:-}"
  local _char _typed=""
  printf "  ${BOLD}%s${R} ${DIM}(hidden · enter = use default: %s)${R}  " "$prompt" "$default"
  while IFS= read -r -s -n1 _char; do
    if [ -z "$_char" ]; then
      break
    elif [ "$_char" = $'\x7f' ] || [ "$_char" = $'\b' ]; then
      if [ -n "$_typed" ]; then
        _typed="${_typed%?}"
        printf '\b \b'
      fi
    else
      _typed+="$_char"
      printf '*'
    fi
  done
  echo ""
  echo ""
  [ -z "$_typed" ] && _pw="$default" || _pw="$_typed"
}

# ── TUI: yes/no ───────────────────────────────────────────────────────────────
tui_yesno() {
  local -n _yn="$1"; shift
  local choice
  tui_select choice "$1" "Yes" "No"
  [ "$choice" = "Yes" ] && _yn=1 || _yn=0
}

# ═════════════════════════════════════════════════════════════════════════════
# Phase 0: Welcome
# ═════════════════════════════════════════════════════════════════════════════
phase_header "0" "Welcome"
echo -e "  This script will guide you through a full NixOS installation."
echo -e ""
echo -e "  ${YE}${BOLD}Requirements:${R}"
echo -e "    ${DIM}▸${R} Booted into a NixOS live ISO"
echo -e "    ${DIM}▸${R} Internet connection active"
echo -e "    ${DIM}▸${R} Target disk(s) visible under /dev/"
echo -e ""
read -r -s -p "  Press Enter to begin..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 1: System Identity
# ═════════════════════════════════════════════════════════════════════════════
phase_header "1" "System Identity"
echo -e "  Configure your username, config path, and login password."
echo ""

tui_input USERNAME "Username" "hogoshi"

_default_dest="/home/$USERNAME/nix-config"
tui_input DEST "Config path" "$_default_dest"

tui_password INIT_PASS "Initial password" "changeme"

echo -e "  ${GR}${BOLD}✓${R} Identity:"
echo -e "    ${DIM}▸${R} User:     ${CY}${USERNAME}${R}"
echo -e "    ${DIM}▸${R} Config:   ${CY}${DEST}${R}"
echo -e "    ${DIM}▸${R} Password: ${CY}${INIT_PASS//?/*}${R}"
echo ""
read -r -s -p "  Press Enter to continue..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 2: Keyboard Layouts
# ═════════════════════════════════════════════════════════════════════════════
phase_header "2" "Keyboard Layouts"
echo -e "  ${GR}${BOLD}English (us)${R} is always included."
echo -e "  Select additional layouts. Cycle with ${CY}Alt+Shift${R}."
echo ""

_KB_OPTS=(
  "Russian    (ru)"
  "Spanish    (es)"
  "German     (de)"
  "French     (fr)"
  "Ukrainian  (ua)"
  "Polish     (pl)"
  "Japanese   (jp)"
  "Italian    (it)"
)

_KB_SELECTED=()
tui_checkbox _KB_SELECTED "Additional layouts:" "${_KB_OPTS[@]}"

KB_LAYOUT="us"
for _l in "${_KB_SELECTED[@]}"; do
  _code="${_l##*(}"
  _code="${_code%)}"
  _code="${_code// /}"
  KB_LAYOUT="${KB_LAYOUT},${_code}"
done

echo -e "  ${GR}${BOLD}✓${R} Active layout string:  ${CY}${BOLD}${KB_LAYOUT}${R}"
echo ""
read -r -s -p "  Press Enter to continue..." _
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# Phase 3: Browser
# ═════════════════════════════════════════════════════════════════════════════
phase_header "3" "Browser"
echo -e "  Choose your default browser."
echo -e "  ${DIM}Zen Browser requires fetching from GitHub (github.com/youwen5/zen-browser-flake).${R}"
echo ""

tui_select BROWSER_CHOICE "Browser:" "Firefox" "Zen Browser"

# ═════════════════════════════════════════════════════════════════════════════
# Phase 4: Disks to Format
# ═════════════════════════════════════════════════════════════════════════════
phase_header "4" "Disks to Format"

mapfile -t ALL_DISKS < <(lsblk -dpno NAME,SIZE,MODEL \
  | grep -E '^/dev/(sd|nvme|vd)' \
  | awk '{printf "%s  (%s  %s)\n", $1, $2, $3}')

if [ ${#ALL_DISKS[@]} -eq 0 ]; then
  err "No disks detected. Is the system booted correctly?"
  show_cursor; exit 1
fi

FORMAT_DISKS=()
while [ ${#FORMAT_DISKS[@]} -eq 0 ]; do
  tui_checkbox FORMAT_DISKS "Select disks to format:" "${ALL_DISKS[@]}"
  if [ ${#FORMAT_DISKS[@]} -eq 0 ]; then
    warn "At least one disk must be selected."
  fi
done

# ═════════════════════════════════════════════════════════════════════════════
# Phase 5: Installation Disk
# ═════════════════════════════════════════════════════════════════════════════
phase_header "5" "Installation Disk"
echo -e "  ${DIM}Select which formatted disk NixOS will be installed on.${R}"
echo ""

PRIMARY_DISK=""
tui_select PRIMARY_DISK "Install NixOS on:" "${FORMAT_DISKS[@]}"
PRIMARY_DEV="${PRIMARY_DISK%% *}"

declare -A MOUNT_PATHS

for disk in "${FORMAT_DISKS[@]}"; do
  dev="${disk%% *}"
  [ "$dev" = "$PRIMARY_DEV" ] && continue
  mount_path=""
  tui_input mount_path "Mount path for ${CY}${dev}${R}" "/hdd"
  MOUNT_PATHS["$dev"]="$mount_path"
done

# ═════════════════════════════════════════════════════════════════════════════
# Phase 6: Install Mode
# ═════════════════════════════════════════════════════════════════════════════
phase_header "6" "Install Mode"
echo -e "  ${BOLD}Auto${R}   — Script formats disk, runs nixos-install, sets everything up."
echo -e "  ${BOLD}Manual${R} — Script only writes config files; you run nixos-install yourself."
echo ""

INSTALL_MODE=""
tui_select INSTALL_MODE "How should NixOS be installed?" "Auto (fully automatic)" "Manual (I will run nixos-install myself)"

AUTO_INSTALL=0
[[ "$INSTALL_MODE" == Auto* ]] && AUTO_INSTALL=1

# ═════════════════════════════════════════════════════════════════════════════
# Phase 7: Write Nix configuration files
# ═════════════════════════════════════════════════════════════════════════════
phase_header "7" "Writing Configuration"

log "Creating ${DEST}..."
mkdir -p "$DEST"

SETUP_HEADER

  echo 'log "Writing nix files..."'

  while IFS= read -r -d '' abs; do
    rel="${abs#$REPO_ROOT/}"
    emit_nix_file "$rel"
  done < <(find "$REPO_ROOT" \
    -not \( -path "$REPO_ROOT/.git/*" -prune \) \
    -not \( -path "$REPO_ROOT/assets/*" -prune \) \
    -not \( -path "$REPO_ROOT/scripts/*" -prune \) \
    -name "*.nix" -print0 | sort -z)

  emit_extra_file "home/programs/firefox-userchrome-template.css"

cat << 'PHASE6_REST'

log "Patching config for user: ${USERNAME}..."
find "$DEST" -name "*.nix" -print0 \
  | xargs -0 sed -i "s|hogoshi|${USERNAME}|g"
sed -i "s|initialPassword = \"[^\"]*\"|initialPassword = \"${INIT_PASS}\"|" \
  "$DEST/modules/system/users.nix"
if [ "$BROWSER_CHOICE" = "Zen Browser" ]; then
  sed -i "s|useZen = false|useZen = true|" "$DEST/flake.nix"
  log "Browser: Zen Browser (useZen = true)"
else
  log "Browser: Firefox (useZen = false)"
fi
ok "Config patched."

log "Setting ownership..."
chown -R "$USERNAME:users" "$DEST" 2>/dev/null \
  || warn "chown failed — user ${USERNAME} may not exist yet on the live ISO"
chmod -R u+rw,go-w "$DEST"

log "Linking /etc/nixos → ${DEST}..."
if sudo rm -rf /etc/nixos && sudo ln -sf "$DEST" /etc/nixos; then
  ok "/etc/nixos linked."
else
  warn "Could not link /etc/nixos — do it manually: sudo ln -sf ${DEST} /etc/nixos"
fi

ok "Configuration written."

# ═════════════════════════════════════════════════════════════════════════════
# Phase 8: Disk Formatting
# ═════════════════════════════════════════════════════════════════════════════
phase_header "8" "Disk Formatting"

if [ "$AUTO_INSTALL" -eq 0 ]; then
  echo -e "  ${DIM}Manual mode — skipping disk formatting.${R}"
  echo ""
  echo -e "  Format ${CY}${PRIMARY_DEV}${R} yourself, then:"
  echo -e "    ${BOLD}sudo nixos-generate-config --root /mnt${R}"
  echo -e "    ${BOLD}sudo nixos-install --flake /etc/nixos#nixos${R}"
  read -r -s -p "  Press Enter to continue..." _
  echo ""
else
  echo -e "  ${YE}${BOLD}WARNING:${R} All data on ${CY}${BOLD}${PRIMARY_DEV}${R} will be destroyed."
  echo ""
  read -r -s -p "  Press Enter to confirm and begin formatting..." _
  echo ""

  log "Partitioning ${PRIMARY_DEV}..."
  if sudo parted -s "$PRIMARY_DEV" -- \
      mklabel gpt \
      mkpart ESP fat32 1MiB 512MiB \
      set 1 esp on \
      mkpart primary ext4 512MiB 100%; then
    ok "Partition table created."
  else
    err "Partitioning failed on ${PRIMARY_DEV}."
  fi

  if [[ "$PRIMARY_DEV" == *nvme* ]]; then
    BOOT_PART="${PRIMARY_DEV}p1"
    ROOT_PART="${PRIMARY_DEV}p2"
  else
    BOOT_PART="${PRIMARY_DEV}1"
    ROOT_PART="${PRIMARY_DEV}2"
  fi

  log "Formatting boot partition (FAT32)..."
  sudo mkfs.fat -F 32 -n BOOT "$BOOT_PART" && ok "Boot: ${BOOT_PART}" \
    || warn "mkfs.fat failed on ${BOOT_PART}"

  log "Formatting root partition (ext4)..."
  sudo mkfs.ext4 -L nixos "$ROOT_PART" && ok "Root: ${ROOT_PART}" \
    || warn "mkfs.ext4 failed on ${ROOT_PART}"

  log "Mounting root..."
  sudo mount "$ROOT_PART" /mnt && ok "Mounted ${ROOT_PART} → /mnt" \
    || err "Mount failed for ${ROOT_PART}"

  sudo mkdir -p /mnt/boot
  sudo mount "$BOOT_PART" /mnt/boot && ok "Mounted ${BOOT_PART} → /mnt/boot" \
    || warn "Boot mount failed for ${BOOT_PART}"

  for dev in "${!MOUNT_PATHS[@]}"; do
    mpath="${MOUNT_PATHS[$dev]}"
    log "Formatting extra disk ${dev} (ext4)..."
    sudo mkfs.ext4 -L "$(basename "$mpath")" "$dev" && ok "Formatted: ${dev}" \
      || warn "mkfs.ext4 failed on ${dev}"
    sudo mkdir -p "/mnt${mpath}"
    sudo mount "$dev" "/mnt${mpath}" && ok "Mounted ${dev} → /mnt${mpath}" \
      || warn "Could not mount ${dev} → /mnt${mpath}"
  done

  log "Generating hardware config..."
  sudo nixos-generate-config --root /mnt && ok "hardware-configuration.nix generated." \
    || warn "nixos-generate-config failed — hardware config may be incomplete"

  GENERATED_HW="/mnt/etc/nixos/hardware-configuration.nix"
  if [ -f "$GENERATED_HW" ]; then
    cp "$GENERATED_HW" "$DEST/hosts/hardware-configuration.nix"
    ok "Copied hardware config to repo."
  else
    warn "Could not find generated hardware-configuration.nix at ${GENERATED_HW}"
  fi
fi

# ═════════════════════════════════════════════════════════════════════════════
# Phase 9: NixOS Installation
# ═════════════════════════════════════════════════════════════════════════════
phase_header "9" "NixOS Installation"

if [ "$AUTO_INSTALL" -eq 0 ]; then
  echo -e "  ${DIM}Manual mode — skipping nixos-install.${R}"
  echo ""
  echo -e "  Run when ready:"
  echo -e "    ${CY}${BOLD}sudo nixos-install --flake /etc/nixos#nixos${R}"
  read -r -s -p "  Press Enter to continue..." _
  echo ""
else
  log "Running nixos-install..."
  echo ""
  if sudo nixos-install --no-root-passwd --flake /etc/nixos#nixos; then
    ok "NixOS installed successfully."
  else
    err "nixos-install failed — check logs above. You may retry manually."
  fi
fi

PHASE6_REST

  emit_asset_links

cat << 'FINAL'

log "Installing ambxst..."
if curl -fsSL get.axeni.de/ambxst | sh; then
  ok "ambxst installed."
else
  warn "ambxst install failed — run manually: curl -fsSL get.axeni.de/ambxst | sh"
fi

log "Running ambxst install hyprland..."
if ambxst install hyprland; then
  ok "ambxst hyprland setup complete."
else
  warn "ambxst install hyprland failed — run manually after reboot."
fi

log "Setting up ~/.config/ambxst..."
mkdir -p "/home/$USERNAME/.config/ambxst"
chown "$USERNAME:users" "/home/$USERNAME/.config/ambxst" 2>/dev/null || true
chmod a+rwx "/home/$USERNAME/.config/ambxst"
ok "~/.config/ambxst ready."

# ═════════════════════════════════════════════════════════════════════════════
# Phase 11: Done
# ═════════════════════════════════════════════════════════════════════════════
phase_header "11" "Complete"

if [ ${#ERRORS[@]} -eq 0 ]; then
  echo -e "  ${GR}${BOLD}All phases completed without errors.${R}"
else
  echo -e "  ${YE}${BOLD}Completed with ${#ERRORS[@]} warning(s):${R}"
  echo ""
  for e in "${ERRORS[@]}"; do
    echo -e "    ${YE}▸${R} ${e}"
  done
fi

echo ""
echo -e "  ${BOLD}Summary:${R}"
echo -e "    ${DIM}▸${R} User:     ${CY}${USERNAME}${R}"
echo -e "    ${DIM}▸${R} Config:   ${CY}${DEST}${R}"
echo -e "    ${DIM}▸${R} Keyboard: ${CY}${KB_LAYOUT}${R}"
echo -e "    ${DIM}▸${R} Browser:  ${CY}${BROWSER_CHOICE}${R}"
echo ""
echo -e "  ${BOLD}Next steps:${R}"
if [ "$AUTO_INSTALL" -eq 1 ]; then
  echo -e "    ${DIM}1.${R} Reboot:                   ${CY}reboot${R}"
  echo -e "    ${DIM}2.${R} Login as:                  ${CY}${USERNAME}${R}  (password: ${CY}${INIT_PASS}${R})"
  echo -e "    ${DIM}3.${R} Open Throne (${CY}Super+K${R}), set up VLESS VPN"
  echo -e "    ${DIM}4.${R} Edit ${CY}${DEST}/flake.nix${R} → set ${CY}setupMode = false${R}"
  echo -e "    ${DIM}5.${R} In kitty (${CY}Super+Enter${R}):   ${CY}rr${R}"
else
  echo -e "    ${DIM}1.${R} Install:  ${CY}sudo nixos-install --flake /etc/nixos#nixos${R}"
  echo -e "    ${DIM}2.${R} Reboot:   ${CY}reboot${R}"
  echo -e "    ${DIM}3.${R} Login as: ${CY}${USERNAME}${R}  (password: ${CY}${INIT_PASS}${R})"
  echo -e "    ${DIM}4.${R} Set up VPN, edit flake → ${CY}setupMode = false${R}, run ${CY}rr${R}"
fi
echo ""
FINAL
}

# ── Main ──────────────────────────────────────────────────────────────────────

builder_header
builder_step "Collecting .nix files..."

NIX_COUNT=$(find "$REPO_ROOT" \
  -not \( -path "$REPO_ROOT/.git/*" -prune \) \
  -not \( -path "$REPO_ROOT/assets/*" -prune \) \
  -not \( -path "$REPO_ROOT/scripts/*" -prune \) \
  -name "*.nix" | wc -l)

builder_ok "Found ${NIX_COUNT} nix files"

builder_step "Collecting assets..."
ASSET_COUNT=$(find "$REPO_ROOT/assets" -maxdepth 1 -name "*.path" 2>/dev/null | wc -l)
builder_ok "Found ${ASSET_COUNT} asset link(s)"

builder_step "Generating ${OUTPUT}..."

emit_setup_script > "$OUTPUT"
chmod +x "$OUTPUT"

builder_ok "Built: $(basename "$OUTPUT")  ($(wc -l < "$OUTPUT") lines)"
echo ""
echo -e "  ${C_DIM}Run on a NixOS live ISO:  bash setup-nixos.sh${C_RESET}"
echo ""
